// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Test for Assignment3', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Test for Assignment3', async function() {
    await driver.get("http://localhost/index.html")
    await driver.manage().window().setRect(1252, 660)
    await driver.findElement(By.linkText("Click here to fill a car sale information")).click()
    await driver.findElement(By.id("btnSave")).click()
  })
})
