// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;

namespace Assignment_3
{

    [TestFixture]
    public class TestforAssignment3Test
    {
        private IWebDriver driver;
        public IDictionary<string, object> vars { get; private set; }
        private IJavaScriptExecutor js;
        [SetUp]
        public void SetUp()
        {
            driver = new ChromeDriver();
            js = (IJavaScriptExecutor)driver;
            vars = new Dictionary<string, object>();
        }
        [TearDown]
        protected void TearDown()
        {
            driver.Quit();
        }
        [Test]
        public void indexPageClickOnClickHereToFillACarSaleInformationReturnInformationForm()
        {
            //Arrange
            driver.Navigate().GoToUrl("http://localhost/index.html");
            driver.Manage().Window.Size = new System.Drawing.Size(1252, 658);

            //Act
            driver.FindElement(By.LinkText("Click here to fill a car sale information")).Click();
            
            //Assert
            Assert.That(driver.FindElement(By.XPath("//h3")).Text, Is.EqualTo("Please enter your contact information and car information in the following form"));
        }
        public void informationForm_NoAnyInputClickSubmit_ReturnRequiredErrorMessageForAllFields()
        {
            //Arrange
            driver.Navigate().GoToUrl("http://localhost/informationForm.html");
            driver.Manage().Window.Size = new System.Drawing.Size(1251, 658);

            //Act
            driver.FindElement(By.Id("btnSave")).Click();

            //Assert
            Assert.That(driver.FindElement(By.Id("firstNameError")).Text, Is.EqualTo("Required an input"));
            Assert.That(driver.FindElement(By.Id("lastNameError")).Text, Is.EqualTo("Required an input"));
            Assert.That(driver.FindElement(By.Id("addressError")).Text, Is.EqualTo("Required an input"));
            Assert.That(driver.FindElement(By.Id("cityError")).Text, Is.EqualTo("Required an input"));
            Assert.That(driver.FindElement(By.Id("provinceError")).Text, Is.EqualTo("Required an input"));
            Assert.That(driver.FindElement(By.Id("pCodeError")).Text, Is.EqualTo("Required an input"));
            Assert.That(driver.FindElement(By.Id("phoneError")).Text, Is.EqualTo("Required an input"));
            Assert.That(driver.FindElement(By.Id("emailError")).Text, Is.EqualTo("Required an input"));
            Assert.That(driver.FindElement(By.Id("makeError")).Text, Is.EqualTo("Required an input"));
            Assert.That(driver.FindElement(By.Id("makeError")).Text, Is.EqualTo("Required an input"));
            Assert.That(driver.FindElement(By.Id("modelError")).Text, Is.EqualTo("Required an input"));
            Assert.That(driver.FindElement(By.Id("yearError")).Text, Is.EqualTo("Required an input"));
        }
        [Test]
        public void informationForm_Input300SSSSAsAddress_ReturnInvalidErrorMessage()
        {
            //Arrange
            driver.Navigate().GoToUrl("http://localhost/informationForm.html");
            driver.Manage().Window.Size = new System.Drawing.Size(1251, 658);
            driver.FindElement(By.CssSelector("#infoForm tr:nth-child(1) > td:nth-child(2)")).Click();
            driver.FindElement(By.Id("firstName")).Click();
            driver.FindElement(By.Id("firstName")).SendKeys("Brandon");
            driver.FindElement(By.Id("lastName")).Click();
            driver.FindElement(By.Id("lastName")).SendKeys("Brown");
            driver.FindElement(By.Id("address")).Click();
            driver.FindElement(By.Id("address")).SendKeys("300SSSS");
            driver.FindElement(By.Id("city")).Click();
            driver.FindElement(By.Id("city")).SendKeys("waterloo");
            driver.FindElement(By.Id("province")).Click();
            {
                var dropdown = driver.FindElement(By.Id("province"));
                dropdown.FindElement(By.XPath("//option[. = 'ONTARIO']")).Click();
            }
            driver.FindElement(By.Id("pCode")).Click();
            driver.FindElement(By.Id("pCode")).SendKeys("4H8 J9L");
            driver.FindElement(By.Id("phone")).Click();
            driver.FindElement(By.Id("phone")).SendKeys("123-123-1234");
            driver.FindElement(By.Id("email")).Click();
            driver.FindElement(By.Id("email")).SendKeys("bb@gamil.com");
            driver.FindElement(By.Id("make")).Click();
            driver.FindElement(By.Id("make")).SendKeys("bmw");
            driver.FindElement(By.Id("model")).Click();
            driver.FindElement(By.Id("model")).SendKeys("1 series");
            driver.FindElement(By.Id("year")).Click();
            driver.FindElement(By.Id("year")).SendKeys("2009");

            //Act
            driver.FindElement(By.Id("btnSave")).Click();

            //Assert
            Assert.That(driver.FindElement(By.Id("addressError")).Text, Is.EqualTo("Invalid. Please start with number and at least two strings after and have spaces in between"));
        }
        [Test]
        public void informationForm_Input123NH0AsPostCode_ReturnInvalidErrorMessage()
        {
            //Arrange
            driver.Navigate().GoToUrl("http://localhost/informationForm.html");
            driver.Manage().Window.Size = new System.Drawing.Size(1251, 658);
            driver.FindElement(By.Id("firstName")).Click();
            driver.FindElement(By.Id("firstName")).SendKeys("Brandon");
            driver.FindElement(By.Id("lastName")).Click();
            driver.FindElement(By.Id("lastName")).SendKeys("Brown");
            driver.FindElement(By.Id("address")).Click();
            driver.FindElement(By.Id("address")).SendKeys("12 King street");
            driver.FindElement(By.Id("city")).Click();
            driver.FindElement(By.Id("city")).SendKeys("waterloo");
            driver.FindElement(By.Id("province")).Click();
            {
                var dropdown = driver.FindElement(By.Id("province"));
                dropdown.FindElement(By.XPath("//option[. = 'ONTARIO']")).Click();
            }
            driver.FindElement(By.Id("pCode")).Click();
            driver.FindElement(By.Id("pCode")).SendKeys("d4f dde");
            driver.FindElement(By.Id("phone")).Click();
            driver.FindElement(By.Id("phone")).SendKeys("123-123-1234");
            driver.FindElement(By.Id("email")).Click();
            driver.FindElement(By.Id("email")).SendKeys("db@gamil.com");
            driver.FindElement(By.Id("make")).Click();
            driver.FindElement(By.Id("make")).SendKeys("fiat");
            driver.FindElement(By.Id("model")).Click();
            driver.FindElement(By.Id("model")).SendKeys("124 spider");
            driver.FindElement(By.Id("year")).Click();
            driver.FindElement(By.Id("year")).SendKeys("2019");

            //Act
            driver.FindElement(By.Id("btnSave")).Click();

            //Assert
            Assert.That(driver.FindElement(By.Id("pCodeError")).Text, Is.EqualTo("Invalid. Please enter e.g 9X9 X9X, X->letters, 9->digts"));
        }
        [Test]
        public void informationForm_Input1234567890AsPhoneNumber_ReturnInvalidErrorMessage()
        {
            //Arrange
            driver.Navigate().GoToUrl("http://localhost/informationForm.html");
            driver.Manage().Window.Size = new System.Drawing.Size(1251, 658);
            driver.FindElement(By.Id("firstName")).Click();
            driver.FindElement(By.Id("firstName")).SendKeys("Brandon");
            driver.FindElement(By.Id("lastName")).Click();
            driver.FindElement(By.Id("lastName")).SendKeys("Brown");
            driver.FindElement(By.Id("address")).Click();
            driver.FindElement(By.Id("address")).SendKeys("12 King street");
            driver.FindElement(By.Id("city")).Click();
            driver.FindElement(By.Id("city")).SendKeys("waterloo");
            driver.FindElement(By.Id("province")).Click();
            {
                var dropdown = driver.FindElement(By.Id("province"));
                dropdown.FindElement(By.XPath("//option[. = 'ONTARIO']")).Click();
            }
            driver.FindElement(By.Id("pCode")).Click();
            driver.FindElement(By.Id("pCode")).SendKeys("7h8 k0p");
            driver.FindElement(By.Id("phone")).Click();
            driver.FindElement(By.Id("phone")).SendKeys("1234567890");
            driver.FindElement(By.Id("email")).Click();
            driver.FindElement(By.Id("email")).SendKeys("db@gmail.com");
            driver.FindElement(By.Id("make")).Click();
            driver.FindElement(By.Id("make")).SendKeys("bmw");
            driver.FindElement(By.Id("model")).Click();
            driver.FindElement(By.Id("model")).SendKeys("1 series");
            driver.FindElement(By.Id("year")).Click();
            driver.FindElement(By.Id("year")).SendKeys("2009");

            //Act
            driver.FindElement(By.Id("btnSave")).Click();

            //Assert
            Assert.That(driver.FindElement(By.Id("phoneError")).Text, Is.EqualTo("Invalid. Please enter e.g 123-123-1234 or (123)-1123-1234"));
        }
        [Test]
        public void informationForm_InputDbAtgmail_ReturnInvalidErrorMessage()
        {
            //Arrange
            driver.Navigate().GoToUrl("http://localhost/informationForm.html");
            driver.Manage().Window.Size = new System.Drawing.Size(1251, 658);
            driver.FindElement(By.Id("firstName")).Click();
            driver.FindElement(By.Id("firstName")).SendKeys("Brandon");
            driver.FindElement(By.Id("lastName")).Click();
            driver.FindElement(By.Id("lastName")).SendKeys("Brown");
            driver.FindElement(By.Id("address")).Click();
            driver.FindElement(By.Id("address")).SendKeys("12 King Street");
            driver.FindElement(By.Id("city")).Click();
            driver.FindElement(By.Id("city")).SendKeys("waterloo");
            driver.FindElement(By.Id("province")).Click();
            {
                var dropdown = driver.FindElement(By.Id("province"));
                dropdown.FindElement(By.XPath("//option[. = 'ONTARIO']")).Click();
            }
            driver.FindElement(By.Id("pCode")).Click();
            driver.FindElement(By.Id("pCode")).SendKeys("4f8 j9l");
            driver.FindElement(By.Id("phone")).Click();
            driver.FindElement(By.Id("phone")).SendKeys("123-123-1234");
            driver.FindElement(By.Id("email")).Click();
            driver.FindElement(By.Id("email")).SendKeys("db@gmail");
            driver.FindElement(By.Id("make")).Click();
            driver.FindElement(By.Id("make")).SendKeys("fiat");
            driver.FindElement(By.Id("model")).Click();
            driver.FindElement(By.Id("model")).SendKeys("spider");
            driver.FindElement(By.Id("year")).Click();
            driver.FindElement(By.Id("year")).SendKeys("2019");

            //Act
            driver.FindElement(By.Id("btnSave")).Click();

            //Assert
            Assert.That(driver.FindElement(By.Id("emailError")).Text, Is.EqualTo("Invalid input"));
        }
        [Test]
        public void informationForm_Input1889AsYear_ReturnInvalidErrorMessage()
        {
            //Arrange
            driver.Navigate().GoToUrl("http://localhost/informationForm.html");
            driver.Manage().Window.Size = new System.Drawing.Size(1251, 658);
            driver.FindElement(By.Id("firstName")).Click();
            driver.FindElement(By.Id("firstName")).SendKeys("Brandon");
            driver.FindElement(By.Id("lastName")).Click();
            driver.FindElement(By.Id("lastName")).SendKeys("Brown");
            driver.FindElement(By.Id("address")).Click();
            driver.FindElement(By.Id("address")).SendKeys("12 king street");
            driver.FindElement(By.Id("city")).Click();
            driver.FindElement(By.Id("city")).SendKeys("waterloo");
            driver.FindElement(By.Id("province")).Click();
            {
                var dropdown = driver.FindElement(By.Id("province"));
                dropdown.FindElement(By.XPath("//option[. = 'ONTARIO']")).Click();
            }
            driver.FindElement(By.Id("pCode")).Click();
            driver.FindElement(By.Id("pCode")).SendKeys("4h8 k9l");
            driver.FindElement(By.Id("phone")).Click();
            driver.FindElement(By.Id("phone")).SendKeys("123-123-1234");
            driver.FindElement(By.Id("email")).Click();
            driver.FindElement(By.Id("email")).SendKeys("db@gamil.com");
            driver.FindElement(By.Id("make")).Click();
            driver.FindElement(By.Id("make")).SendKeys("bmw");
            driver.FindElement(By.Id("model")).Click();
            driver.FindElement(By.Id("model")).SendKeys("1 series");
            driver.FindElement(By.Id("year")).Click();
            driver.FindElement(By.Id("year")).SendKeys("1889");

            //Act
            driver.FindElement(By.Id("btnSave")).Click();

            //Assert
            Assert.That(driver.FindElement(By.Id("yearError")).Text, Is.EqualTo("Invalid. Year start with 19 or 20"));
        }
        [Test]
        public void informationForm_InputValidInformationForEveryField_ReturnOuputOfSellerAndCarInfoAndCarLink()
        {
            //Arrange
            driver.Navigate().GoToUrl("http://localhost/informationForm.html");
            driver.Manage().Window.Size = new System.Drawing.Size(1251, 658);
            driver.FindElement(By.Id("firstName")).Click();
            driver.FindElement(By.Id("firstName")).SendKeys("Brandon");
            driver.FindElement(By.Id("lastName")).Click();
            driver.FindElement(By.Id("lastName")).SendKeys("Brown");
            driver.FindElement(By.Id("address")).Click();
            driver.FindElement(By.Id("address")).SendKeys("12 king street");
            driver.FindElement(By.Id("city")).Click();
            driver.FindElement(By.Id("city")).SendKeys("waterloo");
            driver.FindElement(By.Id("province")).Click();
            {
                var dropdown = driver.FindElement(By.Id("province"));
                dropdown.FindElement(By.XPath("//option[. = 'ONTARIO']")).Click();
            }
            driver.FindElement(By.Id("pCode")).Click();
            driver.FindElement(By.Id("pCode")).SendKeys("8h9 i7y");
            driver.FindElement(By.Id("phone")).Click();
            driver.FindElement(By.Id("phone")).SendKeys("123-123-1234");
            driver.FindElement(By.Id("email")).Click();
            driver.FindElement(By.Id("email")).SendKeys("db@gmail.com");
            driver.FindElement(By.Id("make")).Click();
            driver.FindElement(By.Id("make")).SendKeys("fiat");
            driver.FindElement(By.Id("model")).Click();
            driver.FindElement(By.Id("model")).SendKeys("124 spider");
            driver.FindElement(By.Id("year")).Click();
            driver.FindElement(By.Id("year")).SendKeys("2019");

            //Act
            driver.FindElement(By.Id("btnSave")).Click();

            //Assert
            Assert.That(driver.FindElement(By.Id("nameOutput")).Text, Is.EqualTo("BRANDON BROWN"));
            Assert.That(driver.FindElement(By.Id("addressOutput")).Text, Is.EqualTo("12 KING STREET"));
            Assert.That(driver.FindElement(By.Id("cityOutput")).Text, Is.EqualTo("WATERLOO"));
            Assert.That(driver.FindElement(By.Id("provinceOutput")).Text, Is.EqualTo("ONTARIO"));
            Assert.That(driver.FindElement(By.Id("pCodeOutput")).Text, Is.EqualTo("8H9 I7Y"));
            Assert.That(driver.FindElement(By.Id("phoneOutput")).Text, Is.EqualTo("123-123-1234"));
            Assert.That(driver.FindElement(By.Id("emailOutput")).Text, Is.EqualTo("DB@GMAIL.COM"));
            Assert.That(driver.FindElement(By.Id("vehicleInfo")).Text, Is.EqualTo("2019 FIAT 124 SPIDER"));
        }
       
        [Test]
        public void indexPage_ClickOnClickToViewListOfSavedInformation_ReturnCarSaleListPage()
        {
            //Arrange
            driver.Navigate().GoToUrl("http://localhost/index.html");
            driver.Manage().Window.Size = new System.Drawing.Size(1251, 658);

            //Act
            driver.FindElement(By.LinkText("Click to view list of saved information")).Click();
            
            //Assert
            Assert.That(driver.FindElement(By.CssSelector("h3")).Text, Is.EqualTo("List of Seller and Car information"));
        }
        [Test]
        public void carSaleList_ClickOnHomePage_ReturnHomePage()
        {
            //Arrange
            driver.Navigate().GoToUrl("http://localhost/carSaleList.html");
            driver.Manage().Window.Size = new System.Drawing.Size(1251, 658);
            
            //Act
            driver.FindElement(By.LinkText("Home Page")).Click();

            //Assert
            Assert.That(driver.FindElement(By.CssSelector("h3")).Text, Is.EqualTo("Welcome to car sale web"));
        }
        [Test]
        public void informationForm_ClickOnCarInfoLink_ReturnCarInfoInJDPower()
        {
            //Arrange
            driver.Navigate().GoToUrl("http://localhost/informationForm.html");
            driver.Manage().Window.Size = new System.Drawing.Size(1251, 658);
            driver.FindElement(By.Id("firstName")).Click();
            driver.FindElement(By.Id("firstName")).SendKeys("Brandon");
            driver.FindElement(By.Id("lastName")).Click();
            driver.FindElement(By.Id("lastName")).SendKeys("Brown");
            driver.FindElement(By.Id("address")).Click();
            driver.FindElement(By.Id("address")).SendKeys("12 king street north");
            driver.FindElement(By.Id("city")).Click();
            driver.FindElement(By.Id("city")).SendKeys("waterloo");
            driver.FindElement(By.Id("province")).Click();
            {
                var dropdown = driver.FindElement(By.Id("province"));
                dropdown.FindElement(By.XPath("//option[. = 'ONTARIO']")).Click();
            }
            driver.FindElement(By.Id("pCode")).Click();
            driver.FindElement(By.Id("pCode")).SendKeys("3f8 i9r");
            driver.FindElement(By.Id("phone")).Click();
            driver.FindElement(By.Id("phone")).SendKeys("123-123-1234");
            driver.FindElement(By.Id("email")).Click();
            driver.FindElement(By.Id("email")).SendKeys("db@gmail.com");
            driver.FindElement(By.Id("make")).Click();
            driver.FindElement(By.Id("make")).SendKeys("fiat");
            driver.FindElement(By.Id("model")).Click();
            driver.FindElement(By.Id("model")).SendKeys("124 spider");
            driver.FindElement(By.Id("year")).Click();
            driver.FindElement(By.Id("year")).SendKeys("2019");

            //Act
            driver.FindElement(By.Id("btnSave")).Click();
            driver.FindElement(By.Id("vehicleInfo")).Click();
            js.ExecuteScript("window.scrollTo(0,209)");
            {
                var element = driver.FindElement(By.CssSelector(".pricing-button"));
                Actions builder = new Actions(driver);
                builder.MoveToElement(element).Perform();
            }

            //Assert
            Assert.That(driver.FindElement(By.CssSelector(".page-heading")).Text, Is.EqualTo("2019 FIAT 124 Spider"));
        }
    }
}


    

